import type { Metadata } from "next";
import "../sass/main.scss";
import Nav from "@/components/Nav";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Nav />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
